import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        <span className={styles.logo2}>
        <Image src="/chef.png" alt="Chef Logo" width={100} height={100} />
        </span>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1 className={styles.logo2}>
        <Image src="/chef.png" alt="Chef Logo" width={100} height={100} />
        </h1>

        <p className={styles.description}>
          Ache o chef que mais combina com você!
        </p>

        <h1 classname={styles.picture1}>
          <Image src="/Foto 1.png" alt="Foto 1" width={1010} height={430} /> 
        </h1>

        <h1 classname={styles.picture3}>
          <Image src="/Foto 3.png" alt="Foto 3" width={1006} height={322} /><Image src="/Foto 2.png" alt="Foto 2" width={500} height={754} /> 

        </h1>
      </main>
      
      


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
